name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up gcloud Cloud SDK environment
      # You may pin to the exact commit or the version.
      # uses: google-github-actions/setup-gcloud@94337306dda8180d967a56932ceb4ddcf01edae7
      uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        service_account_key: ${{ secrets.GCLOUD_SA_KEY }}
        project_id: ${{ secrets.GCLOUD_PROJECT_ID }}
        export_default_credentials: true
            
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    
    - name: Test
      run: |
       cd test
       go test 
      env:
        TERRA_ROOT_DOMAIN: ${{ secrets.ROOT_DOMAIN }}
        TERRA_ZONE_NAME: simplycubed-tool