name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: 'gcloud-auth'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCLOUD_SA_KEY }}'
    - name: Set up gcloud Cloud SDK environment
      uses: google-github-actions/setup-gcloud@v1

            
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.17
    
    - name: Test
      run: |
       cd test
       go test 
      env:
        TERRA_ROOT_DOMAIN: simplycubed.tools
        TERRA_ZONE_NAME: simplycubed-tool